[package]
name = "evolvable"
version = "0.1.0"
authors = ["Alkajatomota <Alkajatomota@gmail.com>"]
edition = "2021"

[dependencies]
num_cpus = "1.16.0"
rand = "0.8.5"
rayon = "1.6.1"

[profile.test]
opt-level = 3
debug = true
